python -m src.main -t_dir data/RFMiD/Training_Set -v_dir data/RFMiD/Validation_Set --dataset rfmid --aumento_datos -b 133  -tp 1424 -tt 16 -or 0 -runs_dir data/runs/test_linformer/ --arch CRATE_enana --paciencia -1 --linformer --lr 0.0005
python -m src.main -t_dir data/RFMiD/Training_Set -v_dir data/RFMiD/Validation_Set --dataset rfmid --aumento_datos -b 133  -tp 1424 -tt 16 -or 0 -runs_dir data/runs/test_linformer/ --arch CRATE_enana --paciencia -1 --linformer --lr 0.0005 --shared_dict
python -m src.main -t_dir data/RFMiD/Training_Set -v_dir data/RFMiD/Validation_Set --dataset rfmid --aumento_datos -b 133  -tp 1424 -tt 16 -or 0 -runs_dir data/runs/test_linformer/ --arch CRATE_enana --paciencia -1 --linformer --lr 0.0005 --shared_u
python -m src.main -t_dir data/RFMiD/Training_Set -v_dir data/RFMiD/Validation_Set --dataset rfmid --aumento_datos -b 133  -tp 1424 -tt 16 -or 0 -runs_dir data/runs/test_linformer/ --arch CRATE_enana --paciencia -1 --linformer --lr 0.0005 --shared_dict --shared_u

python -m src.main -t_dir data/RFMiD/Training_Set -v_dir data/RFMiD/Validation_Set --dataset rfmid --aumento_datos -b 133  -tp 1424 -tt 16 -or 0 -runs_dir data/runs/test_linformer/ --arch CRATE_enana --paciencia -1 --linformer --lr 0.0005 --order second
python -m src.main -t_dir data/RFMiD/Training_Set -v_dir data/RFMiD/Validation_Set --dataset rfmid --aumento_datos -b 133  -tp 1424 -tt 16 -or 0 -runs_dir data/runs/test_linformer/ --arch CRATE_enana --paciencia -1 --linformer --lr 0.0005 --order second --shared_dict
python -m src.main -t_dir data/RFMiD/Training_Set -v_dir data/RFMiD/Validation_Set --dataset rfmid --aumento_datos -b 133  -tp 1424 -tt 16 -or 0 -runs_dir data/runs/test_linformer/ --arch CRATE_enana --paciencia -1 --linformer --lr 0.0005 --order second --shared_u
python -m src.main -t_dir data/RFMiD/Training_Set -v_dir data/RFMiD/Validation_Set --dataset rfmid --aumento_datos -b 133  -tp 1424 -tt 16 -or 0 -runs_dir data/runs/test_linformer/ --arch CRATE_enana --paciencia -1 --linformer --lr 0.0005 --order second --shared_dict --shared_u
